# Created by Indra Mahkota
name: Assemble Release

on:
  workflow_run:
    workflows: ["Scan with Detekt All"]
    types:
      - completed

# Add specific environment from secret
env:
  GITHUB_USERNAME: ${{ secrets.USERNAME }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    name: Assemble App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: chmod +x gradlew && ./gradlew build --dry-run --stacktrace

  generate-release-apk:
    needs: [ build ]
    name: Generate a Release apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Assemble Release
        run: chmod +x gradlew && ./gradlew assembleRelease

      - name: Sign Release apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/exploration/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.BASE64_CERT }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: app/exploration/build/outputs/apk/release/exploration-release.apk