# Created by Indra Mahkota
name: Scan with Detekt

on:
  push:
    branches: [ "main" ]

# Add specific environment from secret
env:
  GITHUB_USERNAME: ${{ secrets.USERNAME }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  SSHK: ${{ secrets.SUB_SSHK_A }}

# See: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
jobs:
  scan-with-detekt:
    name: Scan with Detekt
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Submodules
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSHK" > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          git submodule update --init --recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@2.4.2

      - name: Setup Secrets
        run: |
          mkdir -p ./keystore
          echo "${{ secrets.BASE64_CERT }}" | base64 -di > ./keystore/release-key.jks
          echo "${{ secrets.SECRET_PROPERTIES }}" > ./secrets.properties

      - name: Run detekt
        run: chmod +x gradlew && ./gradlew :detektAll --stacktrace

      # Make sure we always run this upload task,
      # because the previous step may fail if there are findings.
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt-reports/detekt.sarif
          category: my-detekt-analysis-tool