# Created by Indra Mahkota
name: Main-Workflows

on:
  push:
    branches: [ "main" ]

jobs:
  scan-with-detekt:
    uses: indramahkota/android-exploration/.github/workflows/scan-with-detekt.yml@main
    secrets:
      user_id: ${{ secrets.USERNAME }}
      user_token: ${{ secrets.TOKEN }}
      user_sshk: ${{ secrets.SUB_SSHK_A }}

  build-project:
    needs: [ scan-with-detekt ]
    uses: indramahkota/android-exploration/.github/workflows/build-project.yml@main
    secrets:
      user_id: ${{ secrets.USERNAME }}
      user_token: ${{ secrets.TOKEN }}
      user_sshk: ${{ secrets.SUB_SSHK_A }}

  assemble-project:
    needs: [ build-project ]
    uses: indramahkota/android-exploration/.github/workflows/assemble-project.yml@main
    secrets:
      user_id: ${{ secrets.USERNAME }}
      user_token: ${{ secrets.TOKEN }}
      user_sshk: ${{ secrets.SUB_SSHK_A }}
      user_base64_cert: ${{ secrets.BASE64_CERT }}
      user_keystore_alias: ${{ secrets.KEYSTORE_ALIAS }}
      user_keystore_pass: ${{ secrets.KEYSTORE_PASSWORD }}
      user_key_pass: ${{ secrets.KEY_PASSWORD }}
